name: Deploy ADF to Azure

on:
  push:
    branches:
      - main
    paths:
      - adf-cicd/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ADF pipeline
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az account set --subscription "<your-subscription-id>"
            az datafactory pipeline create               --resource-group "<your-resource-group>"               --factory-name "<your-adf-name>"               --name "<pipeline-name>"               --pipeline "$(cat adf-cicd/sample-pipeline.json)"
